import { Metric } from '../models/Metric';
import { ContextMatrix } from '../models/ContextMatrix';
import { config } from '../../../config/env';

export type ConsultantMode = 'analysis' | 'strategy' | 'coaching' | 'summary' | 'executive' | 'technical';

/**
 * RelationshipConsultant represents the AI layer of RIP.
 * It does NOT calculate anything. It only interprets the Metrics 
 * generated by the IntelligenceEngine and creates actionable 
 * insights depending on the requested mode.
 */
export class RelationshipConsultant {

    public async consult(metrics: Metric[], context: ContextMatrix, mode: ConsultantMode): Promise<any> {
        const apiKey = config.GOOGLE_API_KEY;
        if (!apiKey) return this.getFallback(context.language);

        const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;
        const isEn = context.language === 'en';
        
        const systemInstruction = isEn ? `
            You are the NAOS Strategic Relationship Consultant. You do not calculate numbers; you interpret them.
            Your goal is NOT to describe the relationship. Your goal is to increase the user's capacity to make better decisions.
            You must answer: what decision is convenient, which is not, what consequences it would have, which scenario has the highest potential, and what risks must be mitigated.
            Treat the relationship as a 'Third Organism'. Do not use esoteric horoscope language.
            Focus on actionable behavioral insights, organizational dynamics, and systemic risks.
            You must return a strictly formatted JSON object following the EXACT structure provided.
        ` : `
            Eres el Consultor Estratégico Relacional de NAOS. No calculas números; los interpretas.
            Tu objetivo NO es describir la relación. Tu objetivo es aumentar la capacidad del usuario para tomar mejores decisiones.
            Debes responder: qué decisión conviene, cuál no, qué consecuencias tendría, cuál escenario tiene mayor potencial, y qué riesgos deben mitigarse.
            Trata a la relación como un 'Tercer Organismo'. No uses lenguaje esotérico de horóscopo.
            Enfócate en recomendaciones conductuales, dinámicas organizacionales y riesgos sistémicos.
            Debes devolver un objeto JSON estrictamente formateado siguiendo la estructura EXACTA provista.
        `;

        const jsonTemplate = `
        {
            "executiveSummary": { "type": "", "potential": "", "risk": "", "coreMemory": "" },
            "modules": [
                {
                    "id": "love", "title": "Love & Emotional Dynamics", "icon": "Heart", "priority": 1,
                    "summary": "", "deepAnalysis": "", "keyInsights": [""], "recommendations": [""],
                    "confidence": 90, "evidence": [""], "limitations": [""], "actions": [{ "step": 1, "action": "" }]
                },
                {
                    "id": "communication", "title": "Communication", "icon": "MessageCircle", "priority": 2,
                    "summary": "", "deepAnalysis": "", "keyInsights": [""], "recommendations": [""],
                    "confidence": 90, "evidence": [""], "limitations": [""], "actions": [{ "step": 1, "action": "" }]
                },
                {
                    "id": "business", "title": "Business & Wealth", "icon": "Briefcase", "priority": 3,
                    "summary": "", "deepAnalysis": "", "keyInsights": [""], "recommendations": [""],
                    "confidence": 90, "evidence": [""], "limitations": [""], "actions": [{ "step": 1, "action": "" }]
                }
                // (Generate at least 8 varied modules like Projects, Family, Spiritual, Shadow, Lifestyle)
            ],
            "scenarios": [
                { "id": "A", "title": "Construir una empresa", "probability": 85, "strengths": [""], "risks": [""], "whatToDo": [""], "description": "" },
                { "id": "B", "title": "Formar una familia", "probability": 70, "strengths": [""], "risks": [""], "whatToDo": [""], "description": "" },
                { "id": "C", "title": "Sociedad profesional sin pareja", "probability": 92, "strengths": [""], "risks": [""], "whatToDo": [""], "description": "" }
            ],
            "contextCompatibility": [
                { "context": "Romance", "score": 85 },
                { "context": "Business", "score": 92 },
                { "context": "Friendship", "score": 95 },
                { "context": "Parenting", "score": 75 },
                { "context": "Travel", "score": 88 },
                { "context": "Living Together", "score": 60 }
            ],
            "topOpportunities": [""],
            "topRisks": [""],
            "actionPlan90Days": [{ "step": 1, "action": "" }]
        }
        `;

        const userPrompt = `
            Context: ${JSON.stringify(context)}
            Metrics: ${JSON.stringify(metrics)}
            
            Return the JSON matching this exact template:
            ${jsonTemplate}
        `;

        try {
            const response = await fetch(API_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    system_instruction: { parts: [{ text: systemInstruction }] },
                    contents: [{ role: "user", parts: [{ text: userPrompt }] }],
                    generationConfig: { temperature: 0.2, response_mime_type: "application/json" }
                })
            });

            if (!response.ok) throw new Error("Gemini API Error");
            const data = await response.json();
            const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text || "{}";
            return JSON.parse(rawText);
        } catch (error) {
            console.warn("⚠️ Consultant Engine failed, using fallback", error);
            return this.getFallback(context.language);
        }
    }

    private getFallback(language: 'es' | 'en') {
        const isEn = language === 'en';
        return {
            executiveSummary: { type: "Fallback", potential: "Unknown", risk: "Unknown", coreMemory: "N/A" },
            modules: [],
            scenarios: [],
            contextCompatibility: [],
            topOpportunities: [],
            topRisks: [],
            actionPlan90Days: []
        };
    }
}
