export const MAJOR_ARCANA_MEANINGS: Record<number, string> = {
    0: "El Loco: Un nuevo comienzo, espontaneidad, fe ciega. El universo te pide que des un salto al vacío con confianza.",
    1: "El Mago: Manifestación, poder personal, recursos. Tienes todas las herramientas necesarias para crear tu realidad.",
    2: "La Sacerdotisa: Intuición, misterio, subconsciente. Escucha tu voz interior; las respuestas no están afuera.",
    3: "La Emperatriz: Abundancia, naturaleza, creatividad. Es momento de gestar, nutrir y permitir que las cosas florezcan.",
    4: "El Emperador: Estructura, autoridad, estabilidad. Pon orden en tu caos y asume el liderazgo de tu vida.",
    5: "El Hierofante: Tradición, guía espiritual, conformidad. Busca sabiduría en lo establecido o en un mentor.",
    6: "Los Enamorados: Unión, decisiones, alineación de valores. Una elección importante se presenta ante ti.",
    7: "El Carro: Voluntad, victoria, dirección. Avanza con determinación y mantén las riendas firmes.",
    8: "La Fuerza: Coraje, compasión, dominio suave. Tu verdadera fuerza reside en tu capacidad de amar y resistir sin violencia.",
    9: "El Ermitaño: Introspección, soledad, guía interior. Retírate un momento para encontrar tu propia luz.",
    10: "La Rueda de la Fortuna: Ciclos, cambio, destino. Todo gira; acepta el movimiento y adáptate al nuevo ciclo.",
    11: "La Justicia: Verdad, causa y efecto, equilibrio. Sé honesto contigo mismo; recibirás lo que has sembrado.",
    12: "El Colgado: Pausa, rendición, nueva perspectiva. A veces hay que detenerse y soltar el control para ver la verdad.",
    13: "La Muerte: Transformación, finales, renacimiento. Deja ir lo que ya no sirve para que lo nuevo pueda nacer.",
    14: "La Templanza: Equilibrio, moderación, alquimia. Mezcla los opuestos con paciencia para encontrar la armonía.",
    15: "El Diablo: Ataduras, materialismo, sombra. Reconoce tus cadenas y adicciones para poder liberarte de ellas.",
    16: "La Torre: Revelación, colapso, despertar súbito. Las estructuras falsas deben caer para construir sobre verdad.",
    17: "La Estrella: Esperanza, inspiración, serenidad. Después de la tormenta, la guía celestial te muestra el camino.",
    18: "La Luna: Ilusión, miedo, subconsciente. No todo es lo que parece; navega tus sombras con intuición.",
    19: "El Sol: Alegría, éxito, vitalidad. La luz brilla sobre ti; disfruta de este momento de claridad y calor.",
    20: "El Juicio: Llamado, absolución, renacimiento. Despierta a tu propósito superior; una segunda oportunidad te espera.",
    21: "El Mundo: Completitud, integración, logro. Un ciclo se cierra con éxito; celebra tu viaje y tu totalidad."
};

export const MAJOR_ARCANA_MEANINGS_EN: Record<number, string> = {
    0: "The Fool: A new beginning, spontaneity, blind faith. The universe asks you to take a leap of faith with confidence.",
    1: "The Magician: Manifestation, personal power, resources. You have all the tools needed to create your reality.",
    2: "The High Priestess: Intuition, mystery, subconscious. Listen to your inner voice; the answers are not outside.",
    3: "The Empress: Abundance, nature, creativity. It is time to gestate, nurture, and allow things to bloom.",
    4: "The Emperor: Structure, authority, stability. Put order in your chaos and take leadership of your life.",
    5: "The Hierophant: Tradition, spiritual guidance, conformity. Seek wisdom in what is established or from a mentor.",
    6: "The Lovers: Union, decisions, alignment of values. An important choice is before you.",
    7: "The Chariot: Will, victory, direction. Advance with determination and hold the reins firm.",
    8: "Strength: Courage, compassion, gentle mastery. Your true strength lies in your ability to love and endure without violence.",
    9: "The Hermit: Introspection, solitude, inner guidance. Withdraw for a moment to find your own light.",
    10: "Wheel of Fortune: Cycles, change, fate. Everything turns; accept the movement and adapt to the new cycle.",
    11: "Justice: Truth, cause and effect, balance. Be honest with yourself; you will receive what you have sown.",
    12: "The Hanged Man: Pause, surrender, new perspective. Sometimes you must stop and let go of control to see the truth.",
    13: "Death: Transformation, endings, rebirth. Let go of what no longer serves so that the new can be born.",
    14: "Temperance: Balance, moderation, alchemy. Mix opposites with patience to find harmony.",
    15: "The Devil: Bonds, materialism, shadow. Recognize your chains and addictions to free yourself from them.",
    16: "The Tower: Revelation, collapse, sudden awakening. False structures must fall to build upon truth.",
    17: "The Star: Hope, inspiration, serenity. After the storm, celestial guidance shows you the way.",
    18: "The Moon: Illusion, fear, subconscious. Not everything is what it seems; navigate your shadows with intuition.",
    19: "The Sun: Joy, success, vitality. The light shines upon you; enjoy this moment of clarity and warmth.",
    20: "Judgement: Calling, absolution, rebirth. Awaken to your higher purpose; a second chance awaits you.",
    21: "The World: Completeness, integration, achievement. A cycle closes successfully; celebrate your journey and your totality."
};

export const NAOS_ARCHETYPE_MEANINGS: Record<number, string> = {
    0: "El Arquitecto: Visión sistémica y diseño de estructuras de largo plazo. Es momento de construir cimientos sólidos.",
    1: "El Estratega: Optimización de recursos y planificación de rutas críticas. Analiza el tablero antes de mover tu pieza.",
    2: "El Custodio: Protección de valores esenciales y mantenimiento de la integridad. Protege lo que es verdaderamente importante.",
    3: "El Alquimista: Transformación de crisis en oportunidades y transmutación de energía. Convierte el plomo de tus problemas en oro.",
    4: "El Comandante: Liderazgo pragmático y ejecución de acciones decisivas. Toma el mando con autoridad y dirección clara.",
    5: "El Orador: Influencia a través del lenguaje y expansión de redes de impacto. Tu voz es tu herramienta de cambio más poderosa.",
    6: "El Visionario: Detección de tendencias futuras y exploración de límites. Mira más allá del horizonte convencional.",
    7: "El Embajador: Diplomacia estratégica y resolución de tensiones externas. Busca alianzas beneficiosas y armonía en el conflicto.",
    8: "El Analista: Procesamiento de datos complejos y búsqueda de eficiencia. Descompón el problema en sus partes fundamentales.",
    9: "El Mediador: Equilibrio de fuerzas opuestas y búsqueda de consenso táctico. Encuentra el punto medio donde todos avanzan.",
    10: "El Explorador: Búsqueda de nuevos territorios y aprendizaje acelerado. Sal de tu zona de confort y descubre lo desconocido.",
    11: "El Guía: Acompañamiento en procesos de evolución y transferencia de sabiduría. Sé la luz que otros necesitan para su camino.",
    12: "El Innovador: Ruptura de paradigmas y hacking de sistemas establecidos. Introduce una solución disruptiva y original.",
    13: "El Guardián: Vigilancia de fronteras y preservación de la seguridad. Asegura tu entorno antes de proceder con la expansión.",
    14: "El Maestro: Dominio técnico y excelencia en la ejecución operativa. Perfecciona tu arte; el detalle es donde reside la maestría.",
    15: "El Mentor: Desarrollo de potencial humano y guía estratégica personalizada. Invierte tiempo en cultivar el talento propio o ajeno."
};

export const NAOS_ARCHETYPE_MEANINGS_EN: Record<number, string> = {
    0: "The Architect: Systemic vision and long-term structure design. It is time to build solid foundations.",
    1: "The Strategist: Resource optimization and critical path planning. Analyze the board before moving your piece.",
    2: "The Custodian: Protection of essential values and maintenance of integrity. Protect what is truly important.",
    3: "The Alchemist: Transforming crises into opportunities and transmuting energy. Turn the lead of your problems into gold.",
    4: "The Commander: Pragmatic leadership and decisive action execution. Take charge with authority and clear direction.",
    5: "The Orator: Influence through language and expanding impact networks. Your voice is your most powerful tool for change.",
    6: "The Visionary: Detection of future trends and boundary exploration. Look beyond the conventional horizon.",
    7: "The Ambassador: Strategic diplomacy and resolution of external tensions. Seek beneficial alliances and harmony in conflict.",
    8: "The Analyst: Processing complex data and seeking efficiency. Break down the problem into its fundamental parts.",
    9: "The Mediator: Balancing opposing forces and seeking tactical consensus. Find the middle point where everyone moves forward.",
    10: "The Explorer: Searching for new territories and accelerated learning. Step out of your comfort zone and discover the unknown.",
    11: "The Guide: Accompaniment in evolution processes and wisdom transfer. Be the light others need for their path.",
    12: "The Innovator: Paradigm breaking and hacking established systems. Introduce a disruptive and original solution.",
    13: "The Guardian: Border surveillance and security preservation. Secure your environment before proceeding with expansion.",
    14: "The Master: Technical mastery and excellence in operational execution. Perfect your art; mastery lies in the detail.",
    15: "The Mentor: Developing human potential and personalized strategic guidance. Invest time in cultivating your own or others' talent."
};

